openapi: 3.0.3
info:
  title: Lab 3 API Specification
  version: 1.0.0
  description: |
    Спецификация эндпоинтов для лабораторной работы №3.
    Реализуйте API строго по этому контракту.

servers:
  - url: http://localhost:8081

tags:
  - name: Users
  - name: Dishes

paths:
  /api/v1/users:
    get:
      tags: [Users]
      operationId: listUsers
      summary: Получить список пользователей
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserResponse"
    post:
      tags: [Users]
      operationId: createUser
      summary: Создать пользователя или вернуть существующего
      description: |
        Если пользователь с тем же уникальным ключом уже существует,
        вернуть существующую сущность и код 200.
        Если пользователя еще нет, создать новую сущность и вернуть код 201.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserCreateRequest"
      responses:
        "200":
          description: Existing user returned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
        "400":
          description: Validation error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/v1/users/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
    get:
      tags: [Users]
      operationId: getUserById
      summary: Получить пользователя по id
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    put:
      tags: [Users]
      operationId: updateUser
      summary: Обновить пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserUpdateRequest"
      responses:
        "200":
          description: Updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
        "400":
          description: Validation error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    delete:
      tags: [Users]
      operationId: deleteUser
      summary: Удалить пользователя
      responses:
        "204":
          description: Deleted
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/v1/dishes:
    get:
      tags: [Dishes]
      operationId: listDishes
      summary: Получить список блюд (опционально с фильтром по имени)
      parameters:
        - name: namePart
          in: query
          required: false
          description: Опциональный фильтр по части имени блюда
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DishResponse"
    post:
      tags: [Dishes]
      operationId: createDish
      summary: Создать блюдо или вернуть существующее
      description: |
        Если блюдо с тем же уникальным ключом уже существует,
        вернуть существующую сущность и код 200.
        Если блюда еще нет, создать новую сущность и вернуть код 201.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DishCreateRequest"
      responses:
        "200":
          description: Existing dish returned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DishResponse"
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DishResponse"
        "400":
          description: Validation error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/v1/dishes/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
    get:
      tags: [Dishes]
      operationId: getDishById
      summary: Получить блюдо по id
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DishResponse"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    put:
      tags: [Dishes]
      operationId: updateDish
      summary: Обновить блюдо
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DishUpdateRequest"
      responses:
        "200":
          description: Updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DishResponse"
        "400":
          description: Validation error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    delete:
      tags: [Dishes]
      operationId: deleteDish
      summary: Удалить блюдо
      responses:
        "204":
          description: Deleted
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    UserCreateRequest:
      type: object
      required: [email, firstName, lastName]
      properties:
        email:
          type: string
          format: email
          example: user@example.com
        firstName:
          type: string
          minLength: 1
          example: Ivan
        lastName:
          type: string
          minLength: 1
          example: Petrov
        isActive:
          type: boolean
          default: true
          example: true

    UserUpdateRequest:
      type: object
      required: [email, firstName, lastName, isActive]
      properties:
        email:
          type: string
          format: email
        firstName:
          type: string
          minLength: 1
        lastName:
          type: string
          minLength: 1
        isActive:
          type: boolean

    UserResponse:
      type: object
      required: [id, email, firstName, lastName, isActive]
      properties:
        id:
          type: integer
          format: int64
        email:
          type: string
          format: email
        firstName:
          type: string
        lastName:
          type: string
        isActive:
          type: boolean

    DishCreateRequest:
      type: object
      required: [name, description, price, isAvailable]
      properties:
        name:
          type: string
          minLength: 1
          example: Margherita
        description:
          type: string
          minLength: 1
          example: Classic pizza with tomato sauce and mozzarella
        price:
          type: number
          format: double
          minimum: 0
          example: 499.0
        isAvailable:
          type: boolean
          example: true

    DishUpdateRequest:
      type: object
      required: [name, description, price, isAvailable]
      properties:
        name:
          type: string
          minLength: 1
        description:
          type: string
          minLength: 1
        price:
          type: number
          format: double
          minimum: 0
        isAvailable:
          type: boolean

    DishResponse:
      type: object
      required: [id, name, description, price, isAvailable]
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        price:
          type: number
          format: double
        isAvailable:
          type: boolean

    ErrorResponse:
      type: object
      required: [status, error, message]
      properties:
        status:
          type: integer
          example: 404
        error:
          type: string
          example: Not Found
        message:
          type: string
          example: User with id=10 not found
